// Mocks generated by Mockito 5.4.6 from annotations
// in expense_tracking_desktop_app/test/unit/services/expense_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:expense_tracking_desktop_app/database/app_database.dart' as _i5;
import 'package:expense_tracking_desktop_app/database/i_database.dart' as _i8;
import 'package:expense_tracking_desktop_app/features/budget/repositories/i_category_budget_manager.dart'
    as _i7;
import 'package:expense_tracking_desktop_app/features/budget/repositories/i_category_reader.dart'
    as _i6;
import 'package:expense_tracking_desktop_app/features/expenses/repositories/i_expense_repository.dart'
    as _i3;
import 'package:expense_tracking_desktop_app/features/expenses/services/i_expense_service.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IExpenseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIExpenseRepository extends _i1.Mock
    implements _i3.IExpenseRepository {
  MockIExpenseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Stream<List<_i4.ExpenseWithCategory>> watchExpensesWithCategory() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchExpensesWithCategory,
          [],
        ),
        returnValue: _i2.Stream<List<_i4.ExpenseWithCategory>>.empty(),
      ) as _i2.Stream<List<_i4.ExpenseWithCategory>>);

  @override
  _i2.Future<int> insertExpense(_i5.ExpensesCompanion? expense) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertExpense,
          [expense],
        ),
        returnValue: _i2.Future<int>.value(0),
      ) as _i2.Future<int>);

  @override
  _i2.Future<bool> updateExpense(_i5.Expense? expense) => (super.noSuchMethod(
        Invocation.method(
          #updateExpense,
          [expense],
        ),
        returnValue: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);

  @override
  _i2.Future<int> deleteExpense(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteExpense,
          [id],
        ),
        returnValue: _i2.Future<int>.value(0),
      ) as _i2.Future<int>);
}

/// A class which mocks [ICategoryReader].
///
/// See the documentation for Mockito's code generation for more information.
class MockICategoryReader extends _i1.Mock implements _i6.ICategoryReader {
  MockICategoryReader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Stream<List<_i5.Category>> watchAllCategories() => (super.noSuchMethod(
        Invocation.method(
          #watchAllCategories,
          [],
        ),
        returnValue: _i2.Stream<List<_i5.Category>>.empty(),
      ) as _i2.Stream<List<_i5.Category>>);

  @override
  _i2.Future<List<_i5.Category>> getAllCategories() => (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [],
        ),
        returnValue: _i2.Future<List<_i5.Category>>.value(<_i5.Category>[]),
      ) as _i2.Future<List<_i5.Category>>);

  @override
  _i2.Future<_i5.Category?> getCategoryById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getCategoryById,
          [id],
        ),
        returnValue: _i2.Future<_i5.Category?>.value(),
      ) as _i2.Future<_i5.Category?>);
}

/// A class which mocks [ICategoryBudgetManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockICategoryBudgetManager extends _i1.Mock
    implements _i7.ICategoryBudgetManager {
  MockICategoryBudgetManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<void> updateCategoryBudget(
    int? categoryId,
    double? budget,
    int? currentVersion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategoryBudget,
          [
            categoryId,
            budget,
            currentVersion,
          ],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> updateCategorySpent(
    int? categoryId,
    double? spent,
    int? currentVersion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategorySpent,
          [
            categoryId,
            spent,
            currentVersion,
          ],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
}

/// A class which mocks [IDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDatabase extends _i1.Mock implements _i8.IDatabase {
  MockIDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<T> transaction<T>(_i2.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                ),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_0<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
              ),
            ),
      ) as _i2.Future<T>);
}
