// Mocks generated by Mockito 5.4.6 from annotations
// in expense_tracking_desktop_app/test/unit/view_models/budget_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i7;
import 'dart:ui' as _i8;

import 'package:expense_tracking_desktop_app/database/app_database.dart' as _i4;
import 'package:expense_tracking_desktop_app/features/budget/repositories/i_category_reader.dart'
    as _i2;
import 'package:expense_tracking_desktop_app/features/budget/repositories/i_category_writer.dart'
    as _i5;
import 'package:expense_tracking_desktop_app/services/error_reporting_service.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ICategoryReader].
///
/// See the documentation for Mockito's code generation for more information.
class MockICategoryReader extends _i1.Mock implements _i2.ICategoryReader {
  MockICategoryReader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Category>> watchAllCategories() => (super.noSuchMethod(
        Invocation.method(
          #watchAllCategories,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.Category>>.empty(),
      ) as _i3.Stream<List<_i4.Category>>);

  @override
  _i3.Future<List<_i4.Category>> getAllCategories() => (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Category>>.value(<_i4.Category>[]),
      ) as _i3.Future<List<_i4.Category>>);

  @override
  _i3.Future<_i4.Category?> getCategoryById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getCategoryById,
          [id],
        ),
        returnValue: _i3.Future<_i4.Category?>.value(),
      ) as _i3.Future<_i4.Category?>);
}

/// A class which mocks [ICategoryWriter].
///
/// See the documentation for Mockito's code generation for more information.
class MockICategoryWriter extends _i1.Mock implements _i5.ICategoryWriter {
  MockICategoryWriter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> insertCategory(_i4.CategoriesCompanion? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertCategory,
          [category],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> updateCategory(_i4.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [category],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCategory(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ErrorReportingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorReportingService extends _i1.Mock
    implements _i6.ErrorReportingService {
  MockErrorReportingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.ErrorReport> get errorHistory => (super.noSuchMethod(
        Invocation.getter(#errorHistory),
        returnValue: <_i6.ErrorReport>[],
      ) as List<_i6.ErrorReport>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reportError(
    String? message, {
    dynamic error,
    StackTrace? stackTrace,
    _i6.ErrorSeverity? severity = _i6.ErrorSeverity.medium,
    String? userId,
    String? screenName,
    Map<String, dynamic>? context,
    bool? handled = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportError,
          [message],
          {
            #error: error,
            #stackTrace: stackTrace,
            #severity: severity,
            #userId: userId,
            #screenName: screenName,
            #context: context,
            #handled: handled,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reportDatabaseError(
    String? operation,
    dynamic error, {
    StackTrace? stackTrace,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportDatabaseError,
          [
            operation,
            error,
          ],
          {
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reportUIError(
    String? screen,
    String? action,
    dynamic error, {
    StackTrace? stackTrace,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportUIError,
          [
            screen,
            action,
            error,
          ],
          {
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reportBusinessLogicError(
    String? operation,
    dynamic error, {
    StackTrace? stackTrace,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportBusinessLogicError,
          [
            operation,
            error,
          ],
          {
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reportValidationError(
    String? field,
    String? validationMessage, {
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportValidationError,
          [
            field,
            validationMessage,
          ],
          {#context: context},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i6.ErrorReport> getErrorsBySeverity(_i6.ErrorSeverity? severity) =>
      (super.noSuchMethod(
        Invocation.method(
          #getErrorsBySeverity,
          [severity],
        ),
        returnValue: <_i6.ErrorReport>[],
      ) as List<_i6.ErrorReport>);

  @override
  List<_i6.ErrorReport> getRecentErrors({int? count = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentErrors,
          [],
          {#count: count},
        ),
        returnValue: <_i6.ErrorReport>[],
      ) as List<_i6.ErrorReport>);

  @override
  List<_i6.ErrorReport> getErrorsByScreen(String? screenName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getErrorsByScreen,
          [screenName],
        ),
        returnValue: <_i6.ErrorReport>[],
      ) as List<_i6.ErrorReport>);

  @override
  Map<String, dynamic> getErrorStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getErrorStatistics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void clearHistory() => super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<_i7.Directory?> getErrorReportsDirectory() => (super.noSuchMethod(
        Invocation.method(
          #getErrorReportsDirectory,
          [],
        ),
        returnValue: _i3.Future<_i7.Directory?>.value(),
      ) as _i3.Future<_i7.Directory?>);

  @override
  _i3.Future<_i7.File?> exportErrorHistory() => (super.noSuchMethod(
        Invocation.method(
          #exportErrorHistory,
          [],
        ),
        returnValue: _i3.Future<_i7.File?>.value(),
      ) as _i3.Future<_i7.File?>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
