// Mocks generated by Mockito 5.4.6 from annotations
// in expense_tracking_desktop_app/test/unit/view_models/edit_expense_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i6;
import 'dart:ui' as _i7;

import 'package:expense_tracking_desktop_app/database/app_database.dart' as _i4;
import 'package:expense_tracking_desktop_app/features/expenses/services/i_expense_service.dart'
    as _i2;
import 'package:expense_tracking_desktop_app/services/error_reporting_service.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IExpenseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIExpenseService extends _i1.Mock implements _i2.IExpenseService {
  MockIExpenseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> createExpense(_i4.ExpensesCompanion? expense) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExpense,
          [expense],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> updateExpense(
    _i4.Expense? oldExpense,
    _i4.Expense? newExpense,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExpense,
          [
            oldExpense,
            newExpense,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteExpense(_i4.Expense? expense) => (super.noSuchMethod(
        Invocation.method(
          #deleteExpense,
          [expense],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i2.ExpenseWithCategory>> watchExpensesWithCategory() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchExpensesWithCategory,
          [],
        ),
        returnValue: _i3.Stream<List<_i2.ExpenseWithCategory>>.empty(),
      ) as _i3.Stream<List<_i2.ExpenseWithCategory>>);
}

/// A class which mocks [ErrorReportingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorReportingService extends _i1.Mock
    implements _i5.ErrorReportingService {
  MockErrorReportingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.ErrorReport> get errorHistory => (super.noSuchMethod(
        Invocation.getter(#errorHistory),
        returnValue: <_i5.ErrorReport>[],
      ) as List<_i5.ErrorReport>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reportError(
    String? message, {
    dynamic error,
    StackTrace? stackTrace,
    _i5.ErrorSeverity? severity = _i5.ErrorSeverity.medium,
    String? userId,
    String? screenName,
    Map<String, dynamic>? context,
    bool? handled = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportError,
          [message],
          {
            #error: error,
            #stackTrace: stackTrace,
            #severity: severity,
            #userId: userId,
            #screenName: screenName,
            #context: context,
            #handled: handled,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reportDatabaseError(
    String? operation,
    dynamic error, {
    StackTrace? stackTrace,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportDatabaseError,
          [
            operation,
            error,
          ],
          {
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reportUIError(
    String? screen,
    String? action,
    dynamic error, {
    StackTrace? stackTrace,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportUIError,
          [
            screen,
            action,
            error,
          ],
          {
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reportBusinessLogicError(
    String? operation,
    dynamic error, {
    StackTrace? stackTrace,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportBusinessLogicError,
          [
            operation,
            error,
          ],
          {
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reportValidationError(
    String? field,
    String? validationMessage, {
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportValidationError,
          [
            field,
            validationMessage,
          ],
          {#context: context},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i5.ErrorReport> getErrorsBySeverity(_i5.ErrorSeverity? severity) =>
      (super.noSuchMethod(
        Invocation.method(
          #getErrorsBySeverity,
          [severity],
        ),
        returnValue: <_i5.ErrorReport>[],
      ) as List<_i5.ErrorReport>);

  @override
  List<_i5.ErrorReport> getRecentErrors({int? count = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentErrors,
          [],
          {#count: count},
        ),
        returnValue: <_i5.ErrorReport>[],
      ) as List<_i5.ErrorReport>);

  @override
  List<_i5.ErrorReport> getErrorsByScreen(String? screenName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getErrorsByScreen,
          [screenName],
        ),
        returnValue: <_i5.ErrorReport>[],
      ) as List<_i5.ErrorReport>);

  @override
  Map<String, dynamic> getErrorStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getErrorStatistics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void clearHistory() => super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<_i6.Directory?> getErrorReportsDirectory() => (super.noSuchMethod(
        Invocation.method(
          #getErrorReportsDirectory,
          [],
        ),
        returnValue: _i3.Future<_i6.Directory?>.value(),
      ) as _i3.Future<_i6.Directory?>);

  @override
  _i3.Future<_i6.File?> exportErrorHistory() => (super.noSuchMethod(
        Invocation.method(
          #exportErrorHistory,
          [],
        ),
        returnValue: _i3.Future<_i6.File?>.value(),
      ) as _i3.Future<_i6.File?>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
